require('dotenv').config()
const express = require('express');
const path = require('path');


const authRouter = require('./routes/auth');

const app = express();
mongoose.connect('mongodb://localhost:27017/fashionStoreDB', {
    useNewUrlParser: true,
    useUnifiedTopology: true
}).then(r => {
    console.log('successfully connected to mongoDB')
})
app.use(express.json());
app.use(express.urlencoded({extended: false}));
app.use(express.static(path.join(__dirname, 'public')));

//header setting middleware
app.use((req, res, next) => {
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader(
        "Access-Control-Allow-Headers",
        "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    );
    res.setHeader(
        "Access-Control-Allow-Methods",
        "GET, POST, PATCH, PUT, DELETE, OPTIONS"
    );
    next();
});

//auth route
app.use('/auth', authRouter);


//error handling middleware
app.use((error, req, res, next) => {
    console.log(error);
    const status = error.statusCode || 500;
    const message = error.message;
    const data = error.data //for validation errors generated by validationErrorHandler
    res.status(status).json({message: message, data: data});
});



module.exports = app;
