require('dotenv').config()
const express = require('express');
const path = require('path');


const authRouter = require('./routes/userRouter');
const itemRouter = require('./routes/itemRouter');

const app = express();

app.use(express.json());
app.use(express.urlencoded({extended: false}));
//app.use(express.static(path.join(__dirname, 'public')));
app.use("public/images", express.static(path.join("backend/public/images")));


//header setting middleware
app.use((req, res, next) => {
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader(
        "Access-Control-Allow-Headers",
        "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    );
    res.setHeader(
        "Access-Control-Allow-Methods",
        "GET, POST, PATCH, PUT, DELETE, OPTIONS"
    );
    next();
});

//auth route
app.use('/api/dev/users', authRouter);
app.use('/api/dev/items', itemRouter);


//error handling middleware
app.use((error, req, res, next) => {
    console.log(error);
    const status = error.statusCode || 500;
    const message = error.message;
    const data = error.data //for validation errors generated by validationErrorHandler
    res.status(status).json({message: message, data: data});
});


module.exports = app;
